### ISSUE TITLE
discard text error

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#234] opened 2023-02-07 23:50 UTC
**Describe the bug**
Asked if I want to discard pig when I clicked on oats and don't have a pig card in my hand.
EDIT: Happened again. 
- Clicked to discard wheat & asked to discard cow. No cow in hand.
- Clicked to discard sheep and was asked to discard wheat. No wheat in hand.

**To Reproduce**
1. This hasn't happened before when I've discarded oats or other cards (I'm on Summer Year 3), so I'm not sure

**Expected behavior**
It should say "Discard Oats?"

**Screenshots**
![Screenshot 2023-02-07 at 18 49 02 (2)](https://user-images.githubusercontent.com/119008588/217393265-a77d54db-2371-44e0-ba88-e5e14961198e.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome/brave

**Comment by GingaaBread** [comment] 2023-02-08 00:56
Duplicate of #134

**Closed by GingaaBread** 2023-02-08 00:56 UTC
